// <auto-generated />
using System;
using LabViroMol.Modules.Scheduling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabViroMol.Modules.Scheduling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    partial class SchedulingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabViroMol.Modules.Scheduling.Domain.Schedules.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AcceptTerm")
                        .HasColumnType("bit")
                        .HasColumnName("AcceptTerm");

                    b.Property<string>("AdvisorProfessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AdvisorProfessor");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApprovedBy");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProjectTitle");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RejectedBy");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RemovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Schedules", "scheduling");
                });

            modelBuilder.Entity("LabViroMol.Modules.Scheduling.Domain.Schedules.Schedule", b =>
                {
                    b.OwnsOne("LabViroMol.Modules.Scheduling.Domain.Schedules.Scheduler", "Scheduler", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Course")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SchedulerCourse");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SchedulerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SchedulerName");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.OwnsOne("LabViroMol.Modules.Scheduling.Domain.Schedules.Scheduling", "Scheduling", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("SchedulingDate");

                            b1.Property<DateTimeOffset>("EndDateHour")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("SchedulingEndHour");

                            b1.Property<DateTimeOffset>("StartDateHour")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("SchedulingStartHour");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("Scheduler")
                        .IsRequired();

                    b.Navigation("Scheduling")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
