// <auto-generated />
using System;
using LabViroMol.Modules.Scheduling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabViroMol.Modules.Scheduling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    partial class SchedulingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabViroMol.Modules.Scheduling.Domain.Schedules.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptTerm")
                        .HasColumnType("boolean")
                        .HasColumnName("AcceptTerm");

                    b.Property<string>("AdvisorProfessor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AdvisorProfessor");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("ApprovedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ProjectTitle");

                    b.Property<string>("RefuseJustification")
                        .HasColumnType("text")
                        .HasColumnName("RefuseJustification");

                    b.Property<Guid?>("RefusedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("RefusedBy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TermUrl")
                        .HasColumnType("text")
                        .HasColumnName("TermUrl");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Schedules", "scheduling");
                });

            modelBuilder.Entity("LabViroMol.Modules.Scheduling.Domain.Schedules.Schedule", b =>
                {
                    b.OwnsMany("LabViroMol.Modules.Scheduling.Domain.Schedules.ScheduleEquipment", "Equipments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EquipmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("EquipmentId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EquipmentName");

                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ScheduleId");

                            b1.ToTable("ScheduleEquipments", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.OwnsOne("LabViroMol.Modules.Scheduling.Domain.Schedules.Scheduler", "Scheduler", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Course")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SchedulerCourse");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SchedulerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SchedulerName");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.OwnsOne("LabViroMol.Modules.Scheduling.Domain.Schedules.Scheduling", "Scheduling", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("SchedulingDate");

                            b1.Property<DateTimeOffset>("EndDateHour")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SchedulingEndHour");

                            b1.Property<DateTimeOffset>("StartDateHour")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SchedulingStartHour");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("Equipments");

                    b.Navigation("Scheduler")
                        .IsRequired();

                    b.Navigation("Scheduling")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
